### ISSUE TITLE
"<" and ">" doesn't rendered correctly in Inline Code Block

### ISSUE THREAD

**Issue by andrewnguyen-dev** [tomitrescak/skillpies-support#4]
It is rendered as  `&lt;` and `&gt;`
![image](https://github.com/user-attachments/assets/e65680e1-2166-4dda-91ef-96bb1373635a)

**Comment by tomitrescak** [comment]
Andrew, I fixed it, but unfortunately, you will just have to re-save all sections where you spot this error. I now pre-render text on server in order to not need send buch of javascript for formatting to client. The pre-rendered text was done during data  conversion.

thank you for reporting this.
