### ISSUE TITLE
All previous comments in Creators Club's discussions disappeared

### ISSUE THREAD

**Issue by andrewnguyen-dev** [tomitrescak/skillpies-support#5]
Seems like this happened when you transition to the new version of Skillpies
![image](https://github.com/user-attachments/assets/cbe712a4-6b3d-4477-a13b-e38f1af3ff3b)

**Comment by tomitrescak** [comment]
Andrew, what am I looking at? I see no error here, what is wrong ?

**Comment by andrewnguyen-dev** [comment]
For example, I wrote comments on this post some days ago, but now there is 0 comment.

**Comment by tomitrescak** [comment]
Andrew, I really appreciate the effort to post these issues, but we need to work on your reporting skills ;)) There was no way for me to deduce that issue from your screenshot. Can you please let me know the url at which this occurs?

Thanks

**Comment by tomitrescak** [comment]
Found the bug and fixed it, thank you for your report!!!

**Comment by andrewnguyen-dev** [comment]
Sorry for the inconvenience cause 😅 Next time I will report in a detail format that you can easily follow/

**Comment by tomitrescak** [comment]
No inconvenience, I was just scratching my brain looking at that image tryoing to figure out whats wrong ;) Thank you for your help!
